# Generated by Django 2.2.19 on 2021-03-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0056_auto_20210314_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Почта'),
        ),
    ]
