# Generated by Django 2.2.19 on 2021-03-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0057_likemodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='likebusinesmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Почта'),
        ),
    ]
