# Generated by Django 2.2.19 on 2021-03-14 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0058_likebusinesmodel_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createbusiness',
            options={'ordering': ['-id'], 'verbose_name': 'Бизенс', 'verbose_name_plural': 'Анкеты бизнес'},
        ),
        migrations.AlterModelOptions(
            name='createneighbour',
            options={'ordering': ['-id'], 'verbose_name': 'Сосед', 'verbose_name_plural': 'Анкеты соседи'},
        ),
        migrations.AlterField(
            model_name='createbusiness',
            name='user_bus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
