# Generated by Django 2.2.19 on 2021-03-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0062_auto_20210314_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='email',
        ),
        migrations.AddField(
            model_name='likemodel',
            name='email_first',
            field=models.CharField(blank=True, max_length=100, verbose_name='Почта хозяйна анкеты'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='email_second',
            field=models.CharField(blank=True, max_length=100, verbose_name='Почта авторизованного'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='like_first',
            field=models.CharField(blank=True, max_length=100, verbose_name='Хозяин анкеты'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='like_second',
            field=models.CharField(blank=True, max_length=100, verbose_name='Авторизированный'),
        ),
    ]
