# Generated by Django 2.2.19 on 2021-03-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0064_likeendmodelne'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='first_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Хозяинa анкеты'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='second_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Почта авторизованного'),
        ),
    ]
