# Generated by Django 2.2.19 on 2021-03-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0065_auto_20210315_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='id_ancket',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID анкеты'),
        ),
    ]
