# Generated by Django 2.2.19 on 2021-03-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0066_likemodel_id_ancket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likebusinesmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='likebusinesmodel',
            name='email_first',
            field=models.CharField(blank=True, max_length=100, verbose_name='Почта хозяйна анкеты'),
        ),
        migrations.AddField(
            model_name='likebusinesmodel',
            name='email_second',
            field=models.CharField(blank=True, max_length=100, verbose_name='Почта авторизованного'),
        ),
        migrations.AddField(
            model_name='likebusinesmodel',
            name='first_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Хозяинa анкеты'),
        ),
        migrations.AddField(
            model_name='likebusinesmodel',
            name='id_ancket',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID анкеты'),
        ),
        migrations.AddField(
            model_name='likebusinesmodel',
            name='second_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Почта авторизованного'),
        ),
    ]
