# Generated by Django 2.2.19 on 2021-03-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0067_auto_20210316_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeEndModelBu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_first', models.CharField(blank=True, max_length=100, verbose_name='Хозяин анкеты')),
                ('email_first', models.CharField(blank=True, max_length=100, verbose_name='Почта хозяйна анкеты')),
                ('like_second', models.CharField(blank=True, max_length=100, verbose_name='Авторизированный')),
                ('email_second', models.CharField(blank=True, max_length=100, verbose_name='Почта авторизованного')),
                ('date_like', models.DateField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Последний лайк бизнес',
                'verbose_name_plural': 'Последние лайки бизнес',
                'db_table': 'like_model_end_b',
            },
        ),
        migrations.AlterModelOptions(
            name='likeendmodelne',
            options={'verbose_name': 'Последний лайк сожителя', 'verbose_name_plural': 'Последние лайки сожителей'},
        ),
    ]
