# Generated by Django 2.2.19 on 2021-03-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0068_auto_20210316_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likebusinesmodel',
            name='id_ancket',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID анкеты'),
        ),
    ]
