# Generated by Django 2.2.19 on 2021-03-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0069_auto_20210316_0708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeEndModelBu',
        ),
    ]
