# Generated by Django 2.2.19 on 2021-03-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0070_delete_likeendmodelbu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeEndModelNe',
        ),
    ]
