# Generated by Django 2.2.19 on 2021-04-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0071_delete_likeendmodelne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createneighbour',
            options={'ordering': ['-id'], 'verbose_name': 'Сосед', 'verbose_name_plural': 'Анкеты соседки'},
        ),
    ]
