# Generated by Django 2.2.19 on 2021-04-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0073_auto_20210418_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='createneighbour',
            name='fathername',
            field=models.CharField(default='', max_length=100, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createneighbour',
            name='surname',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
